import Link from 'next/link';
import { prisma } from '@/lib/db';
import { audienceCount, audienceUrl, parseAudience } from '@/lib/audience-workspace';
export const dynamic = 'force-dynamic';
export default async function Dashboard() {
    const now = new Date();
    const [total, unknown, recorded, followCount, overdue, followUps, drafts, recent, tags, missingNames, missingCities] = await Promise.all([
        audienceCount(parseAudience({})), audienceCount(parseAudience({ status: 'unknown' })), audienceCount(parseAudience({ status: 'recorded' })),
        prisma.contactFollowUp.count({ where: { completedAt: null } }), prisma.contactFollowUp.count({ where: { completedAt: null, dueDate: { lt: now } } }),
        prisma.contactFollowUp.findMany({ where: { completedAt: null }, orderBy: [{ dueDate: { sort: 'asc', nulls: 'last' } }, { id: 'asc' }], take: 5, include: { contact: { select: { fullName: true, email: true } } } }),
        prisma.campaign.findMany({ where: { status: 'DRAFT' }, orderBy: { updatedAt: 'desc' }, take: 4, select: { id: true, name: true, subject: true, updatedAt: true } }),
        prisma.consentEvidence.findMany({ orderBy: { recordedAt: 'desc' }, take: 6, select: { id: true, contactId: true, email: true, source: true, status: true, recordedAt: true } }),
        prisma.tag.findMany({ orderBy: { contacts: { _count: 'desc' } }, take: 8, include: { _count: { select: { contacts: true } } } }),
        audienceCount(parseAudience({quality:'missing_name'})), audienceCount(parseAudience({quality:'missing_city'}))
    ]);
    return <div className="audience-page"><header className="audience-header"><div><p className="eyebrow">THE COMPANY THEATRE / AUDIENCE WORKSPACE</p><h1>A closer connection.</h1><p>A place to know your audience, nurture relationships and prepare what comes next.</p></div><Link className="btn btn-primary btn-md" href="/contacts">Explore audience ↗</Link></header>
 <section className="audience-metrics" aria-label="Audience overview">{[{ label: 'People in your audience', value: total, href: '/contacts', note: 'One record. A richer relationship.' }, { label: 'Opt-in recorded', value: recorded, href: audienceUrl({ status: 'recorded' }), note: 'Recorded opt-in, no current contact block.' }, { label: 'No recorded consent', value: unknown, href: audienceUrl({ status: 'unknown' }), note: 'Mailing flag on; evidence needs review.' }, { label: 'Open follow-ups', value: followCount, href: '#follow-ups', note: `${overdue} overdue · small actions, lasting connections.` }].map(s => <Link href={s.href} key={s.label} className="audience-metric"><span>{s.label}</span><strong>{s.value.toLocaleString()}</strong><small>{s.note}</small></Link>)}</section>
 <section className="audience-quality" aria-label="Complete audience records"><div><strong>Complete the picture.</strong><p>Small details make a more useful audience.</p></div><Link href={audienceUrl({quality:'missing_name'})}><strong>{missingNames.toLocaleString()}</strong> missing names →</Link><Link href={audienceUrl({quality:'missing_city'})}><strong>{missingCities.toLocaleString()}</strong> missing cities →</Link></section>
 <div className="audience-dashboard-grid"><section className="audience-panel audience-section"><div className="audience-section-head"><div><p className="eyebrow">YOUR EXISTING COMMUNITY</p><h2>Find a familiar group.</h2></div><Link href="/tags">All tags →</Link></div><p className="audience-muted">Existing tagged groups, not newly verified attendance or permission.</p><div className="audience-groups">{tags.map(t => <Link key={t.id} href={audienceUrl({ tag: t.name })}><span>{t.name}</span><strong>{t._count.contacts.toLocaleString()} ↗</strong></Link>)}</div>{tags.length === 0 && <p className="audience-empty">No groups yet. Add tags from a person’s record.</p>}</section>
 <section id="follow-ups" className="audience-panel audience-section"><div className="audience-section-head"><div><p className="eyebrow">RELATIONSHIPS</p><h2>The next conversation.</h2></div><span className="badge badge-neutral">{followCount} open</span></div>{followUps.length ? followUps.map(f => <Link className="audience-feed" href={`/contacts/${f.contactId}`} key={f.id}><strong>{f.description}</strong><span>{f.contact.fullName || f.contact.email}</span><small>{f.dueDate ? `${f.dueDate < now ? 'Overdue · ' : ''}${f.dueDate.toLocaleDateString('en-CA', { timeZone: 'America/Toronto' })}` : 'No due date'} · {f.priority} priority</small></Link>) : <div className="audience-empty"><h3>A little follow-through goes a long way.</h3><p>Add a follow-up from any person’s record. Your next conversations will appear here.</p><Link href="/contacts">Find someone →</Link></div>}</section>
 <section className="audience-panel audience-section"><div className="audience-section-head"><div><p className="eyebrow">NEW CONNECTIONS</p><h2>Recent signup requests.</h2></div></div><p className="audience-muted">Recorded requests are not necessarily mailing permissions.</p>{recent.length ? recent.map(e => <Link className="audience-feed" href={`/contacts/${e.contactId}`} key={e.id}><strong>{e.email}</strong><span>{e.source}</span><small>{e.status === 'express_opt_in_recorded' ? 'Opt-in recorded at signup' : 'Review needed'} · {e.recordedAt.toLocaleDateString('en-CA', { timeZone: 'America/Toronto' })}</small></Link>) : <div className="audience-empty"><h3>Ready for the next new face.</h3><p>Website signup evidence will appear here as it arrives. Historical mailing flags are not shown as new signups.</p></div>}</section>
 <section className="audience-panel audience-section"><div className="audience-section-head"><div><p className="eyebrow">ON THE DESK</p><h2>Drafts to work on.</h2></div><Link href="/campaigns">All campaigns →</Link></div>{drafts.map(d => <Link className="audience-feed" key={d.id} href={`/campaigns/${d.id}`}><strong>{d.name}</strong><span>{d.subject}</span><small>Draft · updated {d.updatedAt.toLocaleDateString('en-CA', { timeZone: 'America/Toronto' })}</small></Link>)}{!drafts.length && <p className="audience-empty">No drafts on the desk yet.</p>}<Link className="btn btn-secondary btn-md" href="/campaigns/new">Start a draft</Link><p className="audience-muted">Drafting and design approval never send an email.</p></section></div></div>;
}
