import Link from 'next/link';
import { prisma } from '@/lib/db';
import { audienceCount, audiencePresets, audienceRows, audienceUrl, parseAudience, permissionLabels, type AudienceParams } from '@/lib/audience-workspace';
import QuickTagButton from '@/components/QuickTagButton';
import RemoveTagButton from '@/components/RemoveTagButton';
import AddToTagSearch from '@/components/AddToTagSearch';
export const dynamic = 'force-dynamic';
export default async function ContactsPage({ searchParams }: {
    searchParams: Promise<AudienceParams>;
}) {
    const f = parseAudience(await searchParams);
    const [total, segments, tags, sources] = await Promise.all([audienceCount(f), audiencePresets(), prisma.tag.findMany({ orderBy: { name: 'asc' } }), prisma.consentEvidence.findMany({ distinct: ['source'], select: { source: true }, orderBy: { source: 'asc' } })]);
    const pages = Math.max(1, Math.ceil(total / 50));
    const page = Math.min(f.page, pages);
    const contacts = await audienceRows(f, page);
    const active = Object.entries(f).filter(([k, v]) => !['page', 'sort'].includes(k) && v);
    return <div className="audience-page"><header className="audience-header"><div><p className="eyebrow">THE COMPANY THEATRE / AUDIENCE</p><h1>Your people.</h1><p>Know the person. Build the relationship. Keep permission clear.</p></div><div className="audience-actions"><Link className="btn btn-secondary btn-md" href="/contacts/import">Import</Link><Link className="btn btn-primary btn-md" href="/contacts/new">Add person</Link></div></header>
 <nav className="audience-presets" aria-label="Audience preset views">{segments.map(p => <Link key={p.label} href={audienceUrl(p.filters)} className="audience-preset"><span>{p.label}</span><strong>{p.count.toLocaleString()}</strong></Link>)}</nav>
 <section className="audience-panel"><form className="audience-filters" method="GET" action="/contacts">{f.review && <input type="hidden" name="review" value="1"/>}<label className="audience-search">Find a person<input name="search" defaultValue={f.search} placeholder="Name, email, organisation or context"/></label><label>Permission<select name="status" defaultValue={f.status}><option value="">All permission states</option>{Object.entries(permissionLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Source<select name="source" defaultValue={f.source}><option value="">All recorded signup sources</option>{sources.map(s => <option key={s.source}>{s.source}</option>)}</select></label><label>Tag<select name="tag" defaultValue={f.tag}><option value="">All tags</option>{tags.map(t => <option key={t.id}>{t.name}</option>)}</select></label><label>Order<select name="sort" defaultValue={f.sort}><option value="recent">Recently added</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select></label><label>Relationship<select name="vip" defaultValue={f.vip}><option value="">Everyone</option><option value="1">VIP only</option></select></label><label>Record completeness<select name="quality" defaultValue={f.quality}><option value="">All records</option><option value="missing_name">Missing name</option><option value="missing_city">Missing city</option></select></label><button className="btn btn-primary btn-md">Apply filters</button></form>
 {active.length > 0 && <div className="audience-chips">{active.map(([k, v]) => <Link key={k} href={audienceUrl({ ...f, [k]: '', page: 1 })} className="badge badge-neutral" aria-label={`Remove ${k} filter`}>{k}: {k === 'status' ? permissionLabels[v as keyof typeof permissionLabels] : k === 'quality' ? (v==='missing_name'?'Missing name':'Missing city') : v} ×</Link>)}<Link href="/contacts">Clear all</Link></div>}
 <div className="audience-list-heading"><span><strong>{total.toLocaleString()}</strong> people{total > 0 ? ` · ${(page - 1) * 50 + 1}–${Math.min(page * 50, total)} shown` : ''}</span><a href={audienceUrl(f, '/api/contacts/export')} download>Export this audience ↓</a></div>
 {f.tag && <div className="audience-tag-tools"><span>Manage “{f.tag}”</span><AddToTagSearch tagName={f.tag}/></div>}
 <div className="audience-table-wrap"><table className="audience-table"><thead><tr><th>Person</th><th>Permission & source</th><th>Tags</th><th>Added</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{contacts.map(c => <tr key={c.id}><td><Link className="person-link" href={`/contacts/${c.id}`}><span className="person-initial">{personName(c).slice(0, 1).toUpperCase()}</span><span><strong>{personName(c)}{c.vip ? ' · VIP' : ''}</strong><small>{c.email}</small>{c.organization && <small>{c.organization}</small>}</span></Link></td><td><span className={`permission permission-${c.permission}`}>{permissionLabels[c.permission]}</span><small>{c.latestSource || 'No signup source recorded'}</small></td><td><div className="audience-chips">{c.tags.slice(0, 3).map(({ tag }) => <Link className="badge badge-neutral" key={tag.id} href={audienceUrl({ tag: tag.name })}>{tag.name}</Link>)}{c.tags.length > 3 && <span>+{c.tags.length - 3}</span>}</div></td><td><small>{c.createdAt.toLocaleDateString('en-CA', { timeZone: 'America/Toronto', year: 'numeric', month: 'short', day: 'numeric' })}</small></td><td><QuickTagButton contactId={c.id} contactName={personName(c)} existingTagNames={c.tags.map(t => t.tag.name)} allTags={tags}/>{f.tag && <RemoveTagButton contactId={c.id} tagName={f.tag}/>}</td></tr>)}</tbody></table></div>
 {total === 0 && <div className="audience-empty"><h2>No people match these filters.</h2><p>Try a broader search or clear a filter. Your audience has not changed.</p><Link className="btn btn-secondary btn-md" href="/contacts">Reset filters</Link></div>}
 <footer className="audience-list-heading"><p>Permission evidence is separate from a contact’s mailing flag.</p><nav aria-label="Audience pagination" className="audience-actions">{page > 1 && <Link href={audienceUrl({ ...f, page: page - 1 })}>← Previous</Link>}<span>Page {page} of {pages}</span>{page < pages && <Link href={audienceUrl({ ...f, page: page + 1 })}>Next →</Link>}</nav></footer></section></div>;
}

function personName(contact: { fullName: string | null; firstName: string | null; lastName: string | null; email: string }) {
    return contact.fullName?.trim() || [contact.firstName?.trim(),contact.lastName?.trim()].filter(Boolean).join(' ') || contact.email;
}
